### ISSUE TITLE
Configuration readme outdated?

### ISSUE THREAD

**Issue by thrgamon** [yammer/circuitbox#172]
Hi, 

I had a go configuring some defaults using the example in the readme:

```ruby
# config/initializer/circuitbox.rb
  Circuitbox.configure do |config|
    config.default_circuit_store = Circuitbox::MemoryStore.new
    config.default_notifier = Circuitbox::Notifier::Null.new
    config.default_logger = Rails.logger
  end
```

However, I got the following error `undefined method 'default_circuit_store='`. When I use `config.circuit_store` I no longer get the error. Am I missing something or is the readme outdated?

Many thanks, 

Tom

**Comment by matthewshafer** [comment]
Hey @thrgamon, which version of circuitbox are you using? The readme in main should work on 2.0.0.pre4.

If you are using a 1.x version [this readme](https://github.com/yammer/circuitbox/blob/v1.1.1/README.md) would be the one to check out.

**Comment by thrgamon** [comment]
Aha, yeah that's the ticket, thanks!
